name: Automated Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: List files in scripts folder
        run: |
          ls -al scripts

      - name: Extract ClickUp Tickets
        run: |
          node scripts/extract_clickup_tickets.js

      - name: Create Tags and Release Notes
        id: create_release
        run: |
          node scripts/create_tags_and_release_notes.js

      - name: Push Tags and Release Notes
        run: |
          node scripts/push_tags_and_release_notes.js
