name: Create Tag and Release
on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Create Tag and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event.pull_request.merged == true
        run: |
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          TICKET_NUMBER=$(echo ${{ github.event.pull_request.title }} | grep -oP '\[\K[a-zA-Z0-9]+(?=\])' || echo "")
          PR_DESCRIPTION=$(echo ${{ github.event.pull_request.body }} | head -n 2)
          echo "BASE_REF: $BASE_REF"
          echo "TICKET_NUMBER: $TICKET_NUMBER"
          echo "PR_DESCRIPTION: $PR_DESCRIPTION"

          if [[ "$BASE_REF" == "staging" && -n "$TICKET_NUMBER" ]]; then
            CLICKUP_URL="https://app.clickup.com/t/$TICKET_NUMBER"
            git tag "$TICKET_NUMBER" -m "$PR_DESCRIPTION $CLICKUP_URL"
            git push origin "$TICKET_NUMBER"
            PAYLOAD=$(jq -n --arg tn "$TICKET_NUMBER" --arg pd "$PR_DESCRIPTION $CLICKUP_URL" '{tag_name: $tn, name: $tn, body: $pd}')
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -d "$PAYLOAD" "https://api.github.com/repos/${{ github.repository }}/releases"
          elif [[ "$BASE_REF" == "main" ]]; then
            git fetch --all
            git checkout staging
            PARENT_COMMIT=$(git log --merges -n 1 --pretty="%P" | awk '{print $1}')
            NEW_TAGS=$(git tag --contains $PARENT_COMMIT)
            echo "Tags introduced in the latest merge: $NEW_TAGS"

            ALL_TICKETS=""
            ALL_PR_DESCRIPTIONS=""
            for TAG in $NEW_TAGS; do
              CLICKUP_URL="https://app.clickup.com/t/$TAG"
              ALL_TICKETS=$(printf "%s\n%s" "$ALL_TICKETS" "$CLICKUP_URL")
              PR_DESC_FOR_TAG=$(git tag -l "$TAG" --format='%(contents)')
              ALL_PR_DESCRIPTIONS=$(printf "%s\n%s" "$ALL_PR_DESCRIPTIONS" "$PR_DESC_FOR_TAG")
            done
            RELEASE_TAG="release-$(date +%Y%m%d%H%M%S)"
            RELEASE_NOTES=$(printf "Merged Tickets:\n%s\n\nDescriptions:\n%s" "$ALL_TICKETS" "$ALL_PR_DESCRIPTIONS")
            git tag "$RELEASE_TAG" -m "$RELEASE_NOTES"
            git push origin "$RELEASE_TAG"
            PAYLOAD=$(jq -n --arg tn "$RELEASE_TAG" --arg rn "$RELEASE_NOTES" '{tag_name: $tn, name: $tn, body: $rn}')
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" -d "$PAYLOAD" "https://api.github.com/repos/${{ github.repository }}/releases"
          fi
