name: Create Tag and Release
on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Tag and Release
        if: github.event.pull_request.merged == true
        run: |
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          TICKET_NUMBER=$(echo ${{ github.event.pull_request.title }} | grep -oP 'CU-\d+')
          PR_DESCRIPTION=$(echo ${{ github.event.pull_request.body }} | head -n 2)
          echo "BASE_REF: $BASE_REF"
          echo "TICKET_NUMBER: $TICKET_NUMBER"
          echo "PR_DESCRIPTION: $PR_DESCRIPTION"
          if [[ "$BASE_REF" == "staging" ]]; then
            git tag "$TICKET_NUMBER" -m "$PR_DESCRIPTION"
            git push origin "$TICKET_NUMBER"
          elif [[ "$BASE_REF" == "main" ]]; then
            TAGS=$(git tag --merged staging)
            git tag -d $TAGS
            git push origin :$TAGS
            for TAG in $TAGS; do
              git tag "$TAG" -m "Ticket Tag"
              git push origin "$TAG"
            done
          fi
