name: Automated Release

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Extract ClickUp Tickets and First Lines of PR Description
        id: extract_tickets
        run: |
          echo "Running extract_clickup_tickets.js script..."
          node scripts/extract_clickup_tickets.js
          echo "Done extracting ClickUp tickets and first lines."

      - name: Create Tags and Release Notes
        id: create_release
        run: |
          echo "Running create_tags_and_release_notes.js script..."
          node scripts/create_tags_and_release_notes.js
          echo "Done creating tags and release notes."

      - name: Push Tags and Release Notes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a $(cat version.txt) -F release-notes.md
          git push origin --tags
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Use the secret here