name: Create Tag and Release
on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.3.0/gh_2.3.0_linux_amd64.tar.gz -o gh.tar.gz
          tar xzf gh.tar.gz
          sudo mv gh_2.3.0_linux_amd64/bin/gh /usr/local/bin/
          rm -rf gh.tar.gz gh_2.3.0_linux_amd64

      - name: Set up GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GH_TOKEN | gh auth login --with-token

      - name: Create Tag and Release
        if: github.event.pull_request.merged == true
        run: |
          BASE_REF="${{ github.event.pull_request.base.ref }}"
          TICKET_NUMBER=$(echo ${{ github.event.pull_request.title }} | grep -oP '\d+' || echo "")
          PR_DESCRIPTION=$(echo ${{ github.event.pull_request.body }} | head -n 2)
          echo "BASE_REF: $BASE_REF"
          echo "TICKET_NUMBER: $TICKET_NUMBER"
          echo "PR_DESCRIPTION: $PR_DESCRIPTION"
          if [[ "$BASE_REF" == "staging" && -n "$TICKET_NUMBER" ]]; then
            CLICKUP_URL="https://clickup.com/issue/$TICKET_NUMBER"
            git tag "$TICKET_NUMBER" -m "$PR_DESCRIPTION $CLICKUP_URL"
            git push origin "$TICKET_NUMBER"
            gh release create "$TICKET_NUMBER" --title "$TICKET_NUMBER" --notes "$PR_DESCRIPTION $CLICKUP_URL"
          elif [[ "$BASE_REF" == "main" ]]; then
            TAGS=$(git tag --merged main) # Get tags merged into main
            git tag -d $TAGS
            git push origin :$TAGS
            ALL_TICKETS=""
            ALL_PR_DESCRIPTIONS=""
            for TAG in $TAGS; do
              CLICKUP_URL="https://clickup.com/issue/$TAG"
              ALL_TICKETS+="$CLICKUP_URL, "
              PR_DESC_FOR_TAG=$(git tag -l "$TAG" --format='%(contents)')
              ALL_PR_DESCRIPTIONS+="$PR_DESC_FOR_TAG "
            done
            for TAG in $TAGS; do
              git tag "$TAG" -m "Merged Tickets: $ALL_TICKETS $ALL_PR_DESCRIPTIONS"
              git push origin "$TAG"
              gh release create "$TAG" --title "$TAG" --notes "Merged Tickets: $ALL_TICKETS $ALL_PR_DESCRIPTIONS"
            done
          fi

